version: "3.8"
services:
  raceplace_frontend:
    build:
      context: ./raceplace_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - raceplace_backend
    volumes:
      - ./raceplace_frontend:/app
      - /app/node_modules
    networks:
      - app-network

  raceplace_backend:
    build:
      context: ./raceplace_backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
      PRISMA_LOG_LEVEL: info
    volumes:
      - ./raceplace_backend:/app
      - /app/node_modules
    networks:
      - app-network
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  db:
    image: postgres:latest
    ports:
      - "4001:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
